name: Go CI

# Ce workflow se déclenche quand tu pousses du code sur la branche main
# ou quand tu crées une Pull Request vers main.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # récupérer code
    - name: Checkout du code
      uses: actions/checkout@v4

    # installation environnement Go
    - name: Configuration de Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # Assure-toi que cela correspond à la version de ton go.mod

    # dépendances 
    - name: Installation des dépendances
      run: go mod download

    # Vérification que le code compile bien
    - name: Build
      run: go build -v ./...

    #Exécution de tous tes tests unitaires
    - name: Tests Unitaires
      run: go test -v ./...
